export const authLocalization = {
  alreadyHaveAnAccount: "Already have an account?",
  continueWith: "Continue with {{provider}}",
  email: "Email",
  emailPlaceholder: "Enter your email",
  forgotPassword: "Forgot password?",
  invalidResetPasswordToken: "Invalid reset password token",
  magicLink: "Magic link",
  magicLinkSent: "Magic link sent to your email",
  name: "Name",
  namePlaceholder: "Enter your name",
  newPassword: "New password",
  newPasswordPlaceholder: "Enter your new password",
  password: "Password",
  passwordPlaceholder: "Enter your password",
  passwordResetEmailSent: "Password reset email sent",
  passwordResetSuccess: "Password reset successfully",
  needToCreateAnAccount: "Need to create an account?",
  or: "OR",
  rememberYourPassword: "Remember your password?",
  rememberMe: "Remember me",
  resend: "Resend",
  resetPassword: "Reset Password",
  sendMagicLink: "Send Magic Link",
  sendResetLink: "Send Reset Link",
  signIn: "Sign In",
  signUp: "Sign Up",
  verificationEmailSent: "Verification email sent!",
  verifyYourEmail: "Verify your email"
}

export type AuthLocalization = typeof authLocalization
