import type { SocialProvider } from "better-auth/social-providers"
import type { ComponentPropsWithRef, ComponentType } from "react"
import {
  Apple,
  Atlassian,
  Cognito,
  Discord,
  Dropbox,
  Facebook,
  Figma,
  GitHub,
  GitLab,
  Google,
  HuggingFace,
  Kakao,
  Kick,
  Line,
  Linear,
  LinkedIn,
  Microsoft,
  Naver,
  Notion,
  Paybin,
  PayPal,
  Polar,
  Reddit,
  Roblox,
  Salesforce,
  Slack,
  Spotify,
  TikTok,
  Twitch,
  Vercel,
  VK,
  X,
  Zoom
} from "../components/icons"

const NullIcon = (_props: ComponentPropsWithRef<"svg">) => null

export const providerIcons: Record<
  SocialProvider,
  ComponentType<ComponentPropsWithRef<"svg">>
> = {
  apple: Apple,
  atlassian: Atlassian,
  cognito: Cognito,
  discord: Discord,
  dropbox: Dropbox,
  facebook: Facebook,
  figma: Figma,
  github: GitHub,
  gitlab: GitLab,
  google: Google,
  huggingface: HuggingFace,
  kakao: Kakao,
  kick: Kick,
  line: Line,
  linear: Linear,
  linkedin: LinkedIn,
  microsoft: Microsoft,
  naver: Naver,
  notion: Notion,
  paybin: Paybin,
  paypal: PayPal,
  polar: Polar,
  reddit: Reddit,
  roblox: Roblox,
  salesforce: Salesforce,
  slack: Slack,
  spotify: Spotify,
  tiktok: TikTok,
  twitch: Twitch,
  twitter: X,
  vercel: Vercel,
  vk: VK,
  zoom: Zoom
}
