import { type AuthLocalization } from "../../../../src/lib/auth-localization"

export const dutchLocalization: AuthLocalization = {
    account: "Account",
    accounts: "Accounts",
    accountsDescription: "Beheer uw momenteel aangemelde accounts.",
    accountsInstructions: "Log in op een extra account.",
    addAccount: "Account toevoegen",
    addPasskey: "Passkey toevoegen",
    alreadyHaveAnAccount: "Heeft u al een account?",
    avatar: "Avatar",
    avatarDescription: "Klik op de avatar om een aangepaste avatar te uploaden uit uw bestanden.",
    avatarInstructions: "Een avatar is optioneel, maar sterk aanbevolen.",
    backupCodeRequired: "Backup-code is vereist",
    backupCodes: "Backup-codes",
    backupCodesDescription: "Bewaar deze backup-codes op een veilige plaats. U kunt ze gebruiken om toegang te krijgen tot uw account als u uw tweefactorauthenticatiemethode verliest.",
    backupCodePlaceholder: "Backup-code",
    backupCode: "Backup-code",
    backupCodeAction: "Account herstellen",
    cancel: "Annuleren",
    changePassword: "Wachtwoord wijzigen",
    changePasswordDescription: "Voer uw huidige wachtwoord en een nieuw wachtwoord in.",
    changePasswordInstructions: "Gebruik alstublieft minimaal 8 tekens.",
    changePasswordSuccess: "Uw wachtwoord is gewijzigd.",
    confirmPassword: "Wachtwoord bevestigen",
    confirmPasswordPlaceholder: "Wachtwoord bevestigen",
    confirmPasswordRequired: "Wachtwoordbevestiging is vereist",
    continueWithAuthenticator: "Doorgaan met authenticator",
    copiedToClipboard: "Gekopieerd naar klembord",
    copyAllCodes: "Alle codes kopiëren",
    continue: "Doorgaan",
    currentPassword: "Huidig wachtwoord",
    currentPasswordPlaceholder: "Huidig wachtwoord",
    currentSession: "Huidige sessie",
    delete: "Verwijderen",
    deleteAvatar: "Avatar verwijderen",
    deleteAccount: "Account verwijderen",
    deleteAccountDescription: "Verwijder uw account en alle inhoud permanent. Deze actie kan niet ongedaan worden gemaakt, ga dus voorzichtig verder.",
    deleteAccountInstructions: "Bevestig het verwijderen van uw account. Deze actie kan niet ongedaan worden gemaakt, ga dus voorzichtig verder.",
    deleteAccountVerify: "Controleer uw e-mail om de verwijdering van uw account te bevestigen.",
    deleteAccountSuccess: "Uw account is verwijderd.",
    deleteAccountNotFresh: "U moet recentelijk zijn ingelogd om uw account te verwijderen.",
    disable: "Uitschakelen",
    disabledCredentialsDescription: "Kies een provider om in te loggen op uw account",
    dontHaveAnAccount: "Heeft u geen account?",
    email: "E-mail",
    emailDescription: "Voer het e-mailadres in dat u wilt gebruiken om in te loggen.",
    emailInstructions: "Voer een geldig e-mailadres in.",
    emailInvalid: "E-mailadres is ongeldig",
    emailIsTheSame: "E-mail is hetzelfde",
    emailPlaceholder: "m@voorbeeld.nl",
    emailRequired: "E-mailadres is vereist",
    emailVerifyChange: "Controleer uw e-mail om de wijziging te bevestigen.",
    emailVerification: "Controleer uw e-mail voor de bevestigingslink.",
    enable: "Inschakelen",
    error: "Fout",
    isInvalid: "is ongeldig",
    isRequired: "is vereist",
    isTheSame: "is hetzelfde",
    forgotAuthenticator: "Authenticator vergeten?",
    forgotPassword: "Wachtwoord vergeten",
    forgotPasswordAction: "Reset-link versturen",
    forgotPasswordDescription: "Voer uw e-mail in om uw wachtwoord te resetten",
    forgotPasswordEmail: "Controleer uw e-mail voor de link om het wachtwoord te resetten.",
    forgotPasswordLink: "Wachtwoord vergeten?",
    invalidTwoFactorCookie: "Ongeldig tweefactorcookie",
    link: "Koppelen",
    magicLink: "Magische link",
    magicLinkAction: "Magische link versturen",
    magicLinkDescription: "Voer uw e-mail in om een magische link te ontvangen",
    magicLinkEmail: "Controleer uw e-mail voor de magische link",
    emailOTP: "E-mail-code",
    emailOTPSendAction: "Code versturen",
    emailOTPVerifyAction: "Code verifiëren",
    emailOTPDescription: "Voer uw e-mail in om een code te ontvangen",
    emailOTPVerificationSent: "Controleer uw e-mail voor de bevestigingscode.",
    name: "Naam",
    nameDescription: "Voer uw volledige naam of een weergavenaam in.",
    nameInstructions: "Gebruik maximaal 32 tekens.",
    namePlaceholder: "Naam",
    newPassword: "Nieuw wachtwoord",
    newPasswordPlaceholder: "Nieuw wachtwoord",
    newPasswordRequired: "Nieuw wachtwoord is vereist",
    oneTimePassword: "Eenmalig wachtwoord",
    orContinueWith: "Of doorgaan met",
    passkey: "Passkey",
    passkeys: "Passkeys",
    passkeysDescription: "Beheer uw passkeys voor veilig inloggen.",
    passkeysInstructions: "Krijg veilig toegang tot uw account zonder een wachtwoord te gebruiken.",
    password: "Wachtwoord",
    passwordPlaceholder: "Wachtwoord",
    passwordRequired: "Wachtwoord is vereist",
    passwordsDoNotMatch: "Wachtwoorden komen niet overeen",
    providers: "Providers",
    providersDescription: "Verbind uw account met een dienst van derden.",
    recoverAccount: "Account herstellen",
    recoverAccountAction: "Account herstellen",
    recoverAccountDescription: "Voer een backup-code in om toegang te krijgen tot uw account",
    rememberMe: "Onthoud mij",
    resendCode: "Code opnieuw versturen",
    resendVerificationEmail: "Verificatie-e-mail opnieuw versturen",
    resetPassword: "Wachtwoord resetten",
    resetPasswordAction: "Nieuw wachtwoord opslaan",
    resetPasswordDescription: "Voer hieronder uw nieuwe wachtwoord in",
    resetPasswordInvalidToken: "Ongeldige link om wachtwoord te resetten",
    resetPasswordSuccess: "Wachtwoord succesvol gereset",
    requestFailed: "Verzoek mislukt",
    revoke: "Intrekken",
    signIn: "Inloggen",
    signInAction: "Inloggen",
    signInDescription: "Voer hieronder uw e-mail in om in te loggen op uw account",
    signInUsernameDescription: "Voer uw gebruikersnaam of e-mail in om in te loggen op uw account",
    signInWith: "Inloggen met",
    signOut: "Uitloggen",
    signUp: "Registreren",
    signUpAction: "Account aanmaken",
    signUpDescription: "Voer uw gegevens in om een account aan te maken",
    signUpEmail: "Controleer uw e-mail voor de bevestigingslink.",
    sessions: "Sessies",
    sessionsDescription: "Beheer uw actieve sessies en trek toegang in.",
    setPassword: "Wachtwoord instellen",
    setPasswordDescription: "Klik op de knop hieronder om een e-mail te ontvangen om een wachtwoord in te stellen voor uw account.",
    settings: "Instellingen",
    save: "Opslaan",
    security: "Beveiliging",
    switchAccount: "Account wisselen",
    trustDevice: "Dit apparaat vertrouwen",
    twoFactor: "Twee-factor",
    twoFactorAction: "Code verifiëren",
    twoFactorDescription: "Voer uw eenmalige wachtwoord in om door te gaan",
    twoFactorCardDescription: "Voeg een extra beveiligingslaag toe aan uw account.",
    twoFactorDisableInstructions: "Voer uw wachtwoord in om 2FA uit te schakelen.",
    twoFactorEnableInstructions: "Voer uw wachtwoord in om 2FA in te schakelen",
    twoFactorEnabled: "Tweefactorauthenticatie is ingeschakeld",
    twoFactorDisabled: "Tweefactorauthenticatie is uitgeschakeld",
    twoFactorPrompt: "Tweefactorauthenticatie",
    twoFactorTotpLabel: "Scan de QR-code met uw authenticator",
    sendVerificationCode: "Verificatiecode versturen",
    unlink: "Ontkoppelen",
    updatedSuccessfully: "succesvol bijgewerkt",
    username: "Gebruikersnaam",
    usernameDescription: "Voer de gebruikersnaam in die u wilt gebruiken om in te loggen.",
    usernameInstructions: "Gebruik maximaal 32 tekens.",
    usernamePlaceholder: "Gebruikersnaam",
    signInUsernamePlaceholder: "Gebruikersnaam of e-mail",
    verifyYourEmail: "Verifieer uw e-mail",
    verifyYourEmailDescription: "Verifieer uw e-mailadres. Controleer uw inbox voor de bevestigingse-mail. Als u de e-mail niet heeft ontvangen, klik dan op de knop hieronder om deze opnieuw te versturen.",
    goBack: "Terug",
    invalidPassword: "Ongeldig wachtwoord",
    invalidEmailOrPassword: "Ongeldige e-mail of wachtwoord",
    passwordTooShort: "Wachtwoord te kort",
    uploadAvatar: "Avatar uploaden"
}
