// Replace with "@daveyplate/better-auth-ui" import
import { type AuthLocalization } from "../../../../src/lib/auth-localization"

export const frenchLocalization: AuthLocalization = {
    account: "Compte",
    accounts: "Comptes",
    accountsDescription: "Gérez vos comptes actuellement connectés.",
    accountsInstructions: "Connectez-vous à un compte supplémentaire.",
    addAccount: "Ajouter un compte",
    addPasskey: "Ajouter une clé d'accès",
    alreadyHaveAnAccount: "Vous avez déjà un compte ?",
    avatar: "Avatar",
    avatarDescription: "Cliquez sur l'avatar pour télécharger un avatar personnalisé depuis vos fichiers.",
    avatarInstructions: "Un avatar est facultatif mais fortement recommandé.",
    backupCodeRequired: "Le code de secours est requis",
    backupCodes: "Codes de secours",
    backupCodesDescription: "Sauvegardez ces codes de secours dans un endroit sûr. Vous pouvez les utiliser pour accéder à votre compte si vous perdez votre méthode d'authentification à deux facteurs.",
    backupCodePlaceholder: "Code de secours",
    backupCode: "Code de secours",
    backupCodeAction: "Récupérer le compte",
    cancel: "Annuler",
    changePassword: "Changer le mot de passe",
    changePasswordDescription: "Entrez votre mot de passe actuel et un nouveau mot de passe.",
    changePasswordInstructions: "Veuillez utiliser au moins 8 caractères.",
    changePasswordSuccess: "Votre mot de passe a été changé.",
    confirmPassword: "Confirmer le mot de passe",
    confirmPasswordPlaceholder: "Confirmer le mot de passe",
    confirmPasswordRequired: "La confirmation du mot de passe est requise",
    continueWithAuthenticator: "Continuer avec l'authentificateur",
    copiedToClipboard: "Copié dans le presse-papiers",
    copyAllCodes: "Copier tous les codes",
    continue: "Continuer",
    currentPassword: "Mot de passe actuel",
    currentPasswordPlaceholder: "Mot de passe actuel",
    currentSession: "Session actuelle",
    delete: "Supprimer",
    deleteAvatar: "Supprimer l'avatar",
    deleteAccount: "Supprimer le compte",
    deleteAccountDescription: "Supprimez définitivement votre compte et tout son contenu. Cette action n'est pas réversible, veuillez donc continuer avec prudence.",
    deleteAccountInstructions: "Veuillez confirmer la suppression de votre compte. Cette action n'est pas réversible, veuillez donc continuer avec prudence.",
    deleteAccountVerify: "Veuillez vérifier votre e-mail pour confirmer la suppression de votre compte.",
    deleteAccountSuccess: "Votre compte a été supprimé.",
    deleteAccountNotFresh: "Vous devez être récemment connecté pour supprimer votre compte.",
    disable: "Désactiver",
    disabledCredentialsDescription: "Choisissez un fournisseur pour vous connecter à votre compte",
    dontHaveAnAccount: "Vous n'avez pas de compte ?",
    email: "E-mail",
    emailDescription: "Entrez l'adresse e-mail que vous souhaitez utiliser pour vous connecter.",
    emailInstructions: "Veuillez entrer une adresse e-mail valide.",
    emailInvalid: "L'adresse e-mail n'est pas valide",
    emailIsTheSame: "L'e-mail est le même",
    emailPlaceholder: "m@example.com",
    emailRequired: "L'adresse e-mail est requise",
    emailVerifyChange: "Veuillez vérifier votre e-mail pour confirmer le changement.",
    emailVerification: "Veuillez vérifier votre e-mail pour le lien de vérification.",
    enable: "Activer",
    error: "Erreur",
    isInvalid: "n'est pas valide",
    isRequired: "est requis",
    isTheSame: "est le même",
    forgotAuthenticator: "Oublié l'authentificateur ?",
    forgotPassword: "Mot de passe oublié",
    forgotPasswordAction: "Envoyer le lien de réinitialisation",
    forgotPasswordDescription: "Entrez votre e-mail pour réinitialiser votre mot de passe",
    forgotPasswordEmail: "Vérifiez votre e-mail pour le lien de réinitialisation du mot de passe.",
    forgotPasswordLink: "Mot de passe oublié ?",
    invalidTwoFactorCookie: "Cookie d'authentification à deux facteurs invalide",
    link: "Lier",
    magicLink: "Lien magique",
    magicLinkAction: "Envoyer un lien magique",
    magicLinkDescription: "Entrez votre e-mail pour recevoir un lien magique",
    magicLinkEmail: "Vérifiez votre e-mail pour le lien magique",
    emailOTP: "Code par e-mail",
    emailOTPSendAction: "Envoyer le code",
    emailOTPVerifyAction: "Vérifier le code",
    emailOTPDescription: "Entrez votre e-mail pour recevoir un code",
    emailOTPVerificationSent: "Veuillez vérifier votre e-mail pour le code de vérification.",
    name: "Nom",
    nameDescription: "Veuillez entrer votre nom complet ou un nom d'affichage.",
    nameInstructions: "Veuillez utiliser 32 caractères maximum.",
    namePlaceholder: "Nom",
    newPassword: "Nouveau mot de passe",
    newPasswordPlaceholder: "Nouveau mot de passe",
    newPasswordRequired: "Un nouveau mot de passe est requis",
    oneTimePassword: "Mot de passe à usage unique",
    orContinueWith: "Ou continuer avec",
    passkey: "Clé d'accès",
    passkeys: "Clés d'accès",
    passkeysDescription: "Gérez vos clés d'accès pour un accès sécurisé.",
    passkeysInstructions: "Accédez à votre compte en toute sécurité sans mot de passe.",
    password: "Mot de passe",
    passwordPlaceholder: "Mot de passe",
    passwordRequired: "Le mot de passe est requis",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas",
    providers: "Fournisseurs",
    providersDescription: "Connectez votre compte avec un service tiers.",
    recoverAccount: "Récupérer le compte",
    recoverAccountAction: "Récupérer le compte",
    recoverAccountDescription: "Veuillez entrer un code de secours pour accéder à votre compte",
    rememberMe: "Se souvenir de moi",
    resendCode: "Renvoyer le code",
    resendVerificationEmail: "Renvoyer l'e-mail de vérification",
    resetPassword: "Réinitialiser le mot de passe",
    resetPasswordAction: "Enregistrer le nouveau mot de passe",
    resetPasswordDescription: "Entrez votre nouveau mot de passe ci-dessous",
    resetPasswordInvalidToken: "Lien de réinitialisation de mot de passe invalide",
    resetPasswordSuccess: "Mot de passe réinitialisé avec succès",
    requestFailed: "La demande a échoué",
    revoke: "Révoquer",
    signIn: "Se connecter",
    signInAction: "Connexion",
    signInDescription: "Entrez votre e-mail ci-dessous pour vous connecter à votre compte",
    signInUsernameDescription: "Entrez votre nom d'utilisateur ou e-mail pour vous connecter à votre compte",
    signInWith: "Se connecter avec",
    signOut: "Se déconnecter",
    signUp: "S'inscrire",
    signUpAction: "Créer un compte",
    signUpDescription: "Entrez vos informations pour créer un compte",
    signUpEmail: "Vérifiez votre e-mail pour le lien de vérification.",
    sessions: "Sessions",
    sessionsDescription: "Gérez vos sessions actives et révoquez l'accès.",
    setPassword: "Définir le mot de passe",
    setPasswordDescription: "Cliquez sur le bouton ci-dessous pour recevoir un e-mail pour définir un mot de passe pour votre compte.",
    settings: "Paramètres",
    save: "Enregistrer",
    security: "Sécurité",
    switchAccount: "Changer de compte",
    trustDevice: "Faire confiance à cet appareil",
    twoFactor: "Deux facteurs",
    twoFactorAction: "Vérifier le code",
    twoFactorDescription: "Veuillez entrer votre mot de passe à usage unique pour continuer",
    twoFactorCardDescription: "Ajoutez une couche de sécurité supplémentaire à votre compte.",
    twoFactorDisableInstructions: "Veuillez entrer votre mot de passe pour désactiver l'A2F.",
    twoFactorEnableInstructions: "Veuillez entrer votre mot de passe pour activer l'A2F",
    twoFactorEnabled: "L'authentification à deux facteurs a été activée",
    twoFactorDisabled: "L'authentification à deux facteurs a été désactivée",
    twoFactorPrompt: "Authentification à deux facteurs",
    twoFactorTotpLabel: "Scannez le code QR avec votre authentificateur",
    sendVerificationCode: "Envoyer le code de vérification",
    unlink: "Délier",
    updatedSuccessfully: "mis à jour avec succès",
    username: "Nom d'utilisateur",
    usernameDescription: "Entrez le nom d'utilisateur que vous souhaitez utiliser pour vous connecter.",
    usernameInstructions: "Veuillez utiliser 32 caractères maximum.",
    usernamePlaceholder: "Nom d'utilisateur",
    signInUsernamePlaceholder: "Nom d'utilisateur ou e-mail",
    verifyYourEmail: "Vérifiez votre e-mail",
    verifyYourEmailDescription: "Veuillez vérifier votre adresse e-mail. Vérifiez votre boîte de réception pour l'e-mail de vérification. Si vous n'avez pas reçu l'e-mail, cliquez sur le bouton ci-dessous pour le renvoyer.",
    goBack: "Retour",
    invalidPassword: "Mot de passe invalide",
    invalidEmailOrPassword: "E-mail ou mot de passe invalide",
    passwordTooShort: "Mot de passe trop court",
    uploadAvatar: "Télécharger un avatar"
}
