import { type AuthLocalization } from "../../../../src/lib/auth-localization"

export const germanLocalization: AuthLocalization = {
    account: "Konto",
    accounts: "Konten",
    accountsDescription: "Verwalten Sie Ihre derzeit angemeldeten Konten.",
    accountsInstructions: "Melden Sie sich bei einem zusätzlichen Konto an.",
    addAccount: "Konto hinzufügen",
    addPasskey: "Passkey hinzufügen",
    alreadyHaveAnAccount: "Haben Sie bereits ein Konto?",
    avatar: "Avatar",
    avatarDescription: "Klicken Sie auf den Avatar, um einen benutzerdefinierten Avatar aus Ihren Dateien hochzuladen.",
    avatarInstructions: "Ein Avatar ist optional, aber sehr empfehlenswert.",
    backupCodeRequired: "Backup-Code ist erforderlich",
    backupCodes: "Backup-Codes",
    backupCodesDescription: "Bewahren Sie diese Backup-Codes an einem sicheren Ort auf. Sie können sie verwenden, um auf Ihr Konto zuzugreifen, wenn Sie Ihre Zwei-Faktor-Authentifizierungsmethode verlieren.",
    backupCodePlaceholder: "Backup-Code",
    backupCode: "Backup-Code",
    backupCodeAction: "Konto wiederherstellen",
    cancel: "Abbrechen",
    changePassword: "Passwort ändern",
    changePasswordDescription: "Geben Sie Ihr aktuelles Passwort und ein neues Passwort ein.",
    changePasswordInstructions: "Bitte verwenden Sie mindestens 8 Zeichen.",
    changePasswordSuccess: "Ihr Passwort wurde geändert.",
    confirmPassword: "Passwort bestätigen",
    confirmPasswordPlaceholder: "Passwort bestätigen",
    confirmPasswordRequired: "Passwortbestätigung ist erforderlich",
    continueWithAuthenticator: "Mit Authentifikator fortfahren",
    copiedToClipboard: "In die Zwischenablage kopiert",
    copyAllCodes: "Alle Codes kopieren",
    continue: "Fortfahren",
    currentPassword: "Aktuelles Passwort",
    currentPasswordPlaceholder: "Aktuelles Passwort",
    currentSession: "Aktuelle Sitzung",
    delete: "Löschen",
    deleteAvatar: "Avatar löschen",
    deleteAccount: "Konto löschen",
    deleteAccountDescription: "Entfernen Sie Ihr Konto und alle Inhalte dauerhaft. Diese Aktion ist nicht rückgängig zu machen, fahren Sie daher bitte mit Vorsicht fort.",
    deleteAccountInstructions: "Bitte bestätigen Sie die Löschung Ihres Kontos. Diese Aktion ist nicht rückgängig zu machen, fahren Sie daher bitte mit Vorsicht fort.",
    deleteAccountVerify: "Bitte überprüfen Sie Ihre E-Mail, um die Löschung Ihres Kontos zu bestätigen.",
    deleteAccountSuccess: "Ihr Konto wurde gelöscht.",
    deleteAccountNotFresh: "Sie müssen kürzlich angemeldet sein, um Ihr Konto zu löschen.",
    disable: "Deaktivieren",
    disabledCredentialsDescription: "Wählen Sie einen Anbieter, um sich bei Ihrem Konto anzumelden",
    dontHaveAnAccount: "Haben Sie kein Konto?",
    email: "E-Mail",
    emailDescription: "Geben Sie die E-Mail-Adresse ein, die Sie zur Anmeldung verwenden möchten.",
    emailInstructions: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    emailInvalid: "E-Mail-Adresse ist ungültig",
    emailIsTheSame: "E-Mail ist identisch",
    emailPlaceholder: "m@beispiel.de",
    emailRequired: "E-Mail-Adresse ist erforderlich",
    emailVerifyChange: "Bitte überprüfen Sie Ihre E-Mail, um die Änderung zu bestätigen.",
    emailVerification: "Bitte überprüfen Sie Ihre E-Mail auf den Bestätigungslink.",
    enable: "Aktivieren",
    error: "Fehler",
    isInvalid: "ist ungültig",
    isRequired: "ist erforderlich",
    isTheSame: "ist identisch",
    forgotAuthenticator: "Authentifikator vergessen?",
    forgotPassword: "Passwort vergessen",
    forgotPasswordAction: "Zurücksetzungslink senden",
    forgotPasswordDescription: "Geben Sie Ihre E-Mail ein, um Ihr Passwort zurückzusetzen",
    forgotPasswordEmail: "Überprüfen Sie Ihre E-Mail auf den Link zum Zurücksetzen des Passworts.",
    forgotPasswordLink: "Passwort vergessen?",
    invalidTwoFactorCookie: "Ungültiges Zwei-Faktor-Cookie",
    link: "Verknüpfen",
    magicLink: "Magic Link",
    magicLinkAction: "Magic Link senden",
    magicLinkDescription: "Geben Sie Ihre E-Mail ein, um einen Magic Link zu erhalten",
    magicLinkEmail: "Überprüfen Sie Ihre E-Mail auf den Magic Link",
    emailOTP: "E-Mail-Code",
    emailOTPSendAction: "Code senden",
    emailOTPVerifyAction: "Code verifizieren",
    emailOTPDescription: "Geben Sie Ihre E-Mail ein, um einen Code zu erhalten",
    emailOTPVerificationSent: "Bitte überprüfen Sie Ihre E-Mail auf den Bestätigungscode.",
    name: "Name",
    nameDescription: "Bitte geben Sie Ihren vollständigen Namen oder einen Anzeigenamen ein.",
    nameInstructions: "Bitte verwenden Sie maximal 32 Zeichen.",
    namePlaceholder: "Name",
    newPassword: "Neues Passwort",
    newPasswordPlaceholder: "Neues Passwort",
    newPasswordRequired: "Neues Passwort ist erforderlich",
    oneTimePassword: "Einmalpasswort",
    orContinueWith: "Oder fortfahren mit",
    passkey: "Passkey",
    passkeys: "Passkeys",
    passkeysDescription: "Verwalten Sie Ihre Passkeys für sicheren Zugang.",
    passkeysInstructions: "Greifen Sie sicher auf Ihr Konto zu, ohne ein Passwort zu verwenden.",
    password: "Passwort",
    passwordPlaceholder: "Passwort",
    passwordRequired: "Passwort ist erforderlich",
    passwordsDoNotMatch: "Passwörter stimmen nicht überein",
    providers: "Anbieter",
    providersDescription: "Verbinden Sie Ihr Konto mit einem Drittanbieterdienst.",
    recoverAccount: "Konto wiederherstellen",
    recoverAccountAction: "Konto wiederherstellen",
    recoverAccountDescription: "Bitte geben Sie einen Backup-Code ein, um auf Ihr Konto zuzugreifen",
    rememberMe: "Angemeldet bleiben",
    resendCode: "Code erneut senden",
    resendVerificationEmail: "Bestätigungs-E-Mail erneut senden",
    resetPassword: "Passwort zurücksetzen",
    resetPasswordAction: "Neues Passwort speichern",
    resetPasswordDescription: "Geben Sie unten Ihr neues Passwort ein",
    resetPasswordInvalidToken: "Ungültiger Link zum Zurücksetzen des Passworts",
    resetPasswordSuccess: "Passwort erfolgreich zurückgesetzt",
    requestFailed: "Anfrage fehlgeschlagen",
    revoke: "Widerrufen",
    signIn: "Anmelden",
    signInAction: "Anmelden",
    signInDescription: "Geben Sie unten Ihre E-Mail ein, um sich bei Ihrem Konto anzumelden",
    signInUsernameDescription: "Geben Sie Ihren Benutzernamen oder Ihre E-Mail ein, um sich bei Ihrem Konto anzumelden",
    signInWith: "Anmelden mit",
    signOut: "Abmelden",
    signUp: "Registrieren",
    signUpAction: "Konto erstellen",
    signUpDescription: "Geben Sie Ihre Daten ein, um ein Konto zu erstellen",
    signUpEmail: "Überprüfen Sie Ihre E-Mail auf den Bestätigungslink.",
    sessions: "Sitzungen",
    sessionsDescription: "Verwalten Sie Ihre aktiven Sitzungen und widerrufen Sie den Zugriff.",
    setPassword: "Passwort festlegen",
    setPasswordDescription: "Klicken Sie auf die Schaltfläche unten, um eine E-Mail zu erhalten, um ein Passwort für Ihr Konto festzulegen.",
    settings: "Einstellungen",
    save: "Speichern",
    security: "Sicherheit",
    switchAccount: "Konto wechseln",
    trustDevice: "Diesem Gerät vertrauen",
    twoFactor: "Zwei-Faktor",
    twoFactorAction: "Code verifizieren",
    twoFactorDescription: "Bitte geben Sie Ihr Einmalpasswort ein, um fortzufahren",
    twoFactorCardDescription: "Fügen Sie Ihrem Konto eine zusätzliche Sicherheitsebene hinzu.",
    twoFactorDisableInstructions: "Bitte geben Sie Ihr Passwort ein, um 2FA zu deaktivieren.",
    twoFactorEnableInstructions: "Bitte geben Sie Ihr Passwort ein, um 2FA zu aktivieren",
    twoFactorEnabled: "Zwei-Faktor-Authentifizierung wurde aktiviert",
    twoFactorDisabled: "Zwei-Faktor-Authentifizierung wurde deaktiviert",
    twoFactorPrompt: "Zwei-Faktor-Authentifizierung",
    twoFactorTotpLabel: "Scannen Sie den QR-Code mit Ihrem Authentifikator",
    sendVerificationCode: "Bestätigungscode senden",
    unlink: "Verknüpfung aufheben",
    updatedSuccessfully: "erfolgreich aktualisiert",
    username: "Benutzername",
    usernameDescription: "Geben Sie den Benutzernamen ein, den Sie zur Anmeldung verwenden möchten.",
    usernameInstructions: "Bitte verwenden Sie maximal 32 Zeichen.",
    usernamePlaceholder: "Benutzername",
    signInUsernamePlaceholder: "Benutzername oder E-Mail",
    verifyYourEmail: "Bestätigen Sie Ihre E-Mail",
    verifyYourEmailDescription: "Bitte bestätigen Sie Ihre E-Mail-Adresse. Überprüfen Sie Ihren Posteingang auf die Bestätigungs-E-Mail. Wenn Sie die E-Mail nicht erhalten haben, klicken Sie unten auf die Schaltfläche, um sie erneut zu senden.",
    goBack: "Zurück",
    invalidPassword: "Ungültiges Passwort",
    invalidEmailOrPassword: "Ungültige E-Mail oder Passwort",
    passwordTooShort: "Passwort zu kurz",
    uploadAvatar: "Avatar hochladen"
}
