import { type AuthLocalization } from "@daveyplate/better-auth-ui"

export const italianLocalization: AuthLocalization = {
    account: "Account",
    accounts: "Account",
    accountsDescription: "Gestisci i tuoi account attualmente connessi.",
    accountsInstructions: "Accedi a un account aggiuntivo.",
    addAccount: "Aggiungi account",
    addPasskey: "Aggiungi passkey",
    alreadyHaveAnAccount: "Hai già un account?",
    avatar: "Avatar",
    avatarDescription: "Clicca sull'avatar per caricarne uno personalizzato dai tuoi file.",
    avatarInstructions: "Un avatar è opzionale ma fortemente consigliato.",
    backupCodeRequired: "Il codice di backup è obbligatorio",
    backupCodes: "Codici di backup",
    backupCodesDescription: "Salva questi codici di backup in un luogo sicuro. Puoi utilizzarli per accedere al tuo account se perdi il tuo metodo di autenticazione a due fattori.",
    backupCodePlaceholder: "Codice di backup",
    backupCode: "Codice di backup",
    backupCodeAction: "Recupera account",
    cancel: "Annulla",
    changePassword: "Cambia password",
    changePasswordDescription: "Inserisci la tua password attuale e una nuova password.",
    changePasswordInstructions: "Utilizza almeno 8 caratteri.",
    changePasswordSuccess: "La tua password è stata cambiata.",
    confirmPassword: "Conferma password",
    confirmPasswordPlaceholder: "Conferma password",
    confirmPasswordRequired: "La conferma della password è obbligatoria",
    continueWithAuthenticator: "Continua con l'autenticatore",
    copiedToClipboard: "Copiato negli appunti",
    copyAllCodes: "Copia tutti i codici",
    continue: "Continua",
    currentPassword: "Password attuale",
    currentPasswordPlaceholder: "Password attuale",
    currentSession: "Sessione attuale",
    delete: "Elimina",
    deleteAvatar: "Elimina avatar",
    deleteAccount: "Elimina account",
    deleteAccountDescription: "Rimuovi permanentemente il tuo account e tutti i suoi contenuti. Questa azione non è reversibile, quindi procedi con cautela.",
    deleteAccountInstructions: "Conferma l'eliminazione del tuo account. Questa azione non è reversibile, quindi procedi con cautela.",
    deleteAccountVerify: "Controlla la tua email per verificare l'eliminazione del tuo account.",
    deleteAccountSuccess: "Il tuo account è stato eliminato.",
    deleteAccountNotFresh: "Devi aver effettuato l'accesso recentemente per eliminare il tuo account.",
    disable: "Disattiva",
    disabledCredentialsDescription: "Scegli un provider per accedere al tuo account",
    dontHaveAnAccount: "Non hai un account?",
    email: "Email",
    emailDescription: "Inserisci l'indirizzo email che desideri utilizzare per accedere.",
    emailInstructions: "Inserisci un indirizzo email valido.",
    emailInvalid: "L'indirizzo email non è valido",
    emailIsTheSame: "L'email è la stessa",
    emailPlaceholder: "m@esempio.com",
    emailRequired: "L'indirizzo email è obbligatorio",
    emailVerifyChange: "Controlla la tua email per verificare la modifica.",
    emailVerification: "Controlla la tua email per il link di verifica.",
    enable: "Attiva",
    error: "Errore",
    isInvalid: "non è valido",
    isRequired: "è obbligatorio",
    isTheSame: "è lo stesso",
    forgotAuthenticator: "Hai dimenticato l'autenticatore?",
    forgotPassword: "Password dimenticata",
    forgotPasswordAction: "Invia link di ripristino",
    forgotPasswordDescription: "Inserisci la tua email per reimpostare la password",
    forgotPasswordEmail: "Controlla la tua email per il link di reimpostazione della password.",
    forgotPasswordLink: "Hai dimenticato la password?",
    invalidTwoFactorCookie: "Cookie di autenticazione a due fattori non valido",
    link: "Collega",
    magicLink: "Magic Link",
    magicLinkAction: "Invia magic link",
    magicLinkDescription: "Inserisci la tua email per ricevere un magic link",
    magicLinkEmail: "Controlla la tua email per il magic link",
    emailOTP: "Codice email",
    emailOTPSendAction: "Invia codice",
    emailOTPVerifyAction: "Verifica codice",
    emailOTPDescription: "Inserisci la tua email per ricevere un codice",
    emailOTPVerificationSent: "Controlla la tua email per il codice di verifica.",
    name: "Nome",
    nameDescription: "Inserisci il tuo nome completo o un nome visualizzato.",
    nameInstructions: "Utilizza massimo 32 caratteri.",
    namePlaceholder: "Nome",
    newPassword: "Nuova password",
    newPasswordPlaceholder: "Nuova password",
    newPasswordRequired: "La nuova password è obbligatoria",
    oneTimePassword: "Password monouso",
    orContinueWith: "O continua con",
    passkey: "Passkey",
    passkeys: "Passkey",
    passkeysDescription: "Gestisci le tue passkey per un accesso sicuro.",
    passkeysInstructions: "Accedi al tuo account in modo sicuro senza password.",
    password: "Password",
    passwordPlaceholder: "Password",
    passwordRequired: "La password è obbligatoria",
    passwordsDoNotMatch: "Le password non corrispondono",
    providers: "Provider",
    providersDescription: "Connetti il tuo account con un servizio di terze parti.",
    recoverAccount: "Recupera account",
    recoverAccountAction: "Recupera account",
    recoverAccountDescription: "Inserisci un codice di backup per accedere al tuo account",
    rememberMe: "Ricordami",
    resendCode: "Reinvia codice",
    resendVerificationEmail: "Reinvia email di verifica",
    resetPassword: "Reimposta password",
    resetPasswordAction: "Salva nuova password",
    resetPasswordDescription: "Inserisci la tua nuova password qui sotto",
    resetPasswordInvalidToken: "Link di reimpostazione password non valido",
    resetPasswordSuccess: "Password reimpostata con successo",
    requestFailed: "Richiesta fallita",
    revoke: "Revoca",
    signIn: "Accedi",
    signInAction: "Accedi",
    signInDescription: "Inserisci la tua email qui sotto per accedere al tuo account",
    signInUsernameDescription: "Inserisci il tuo nome utente o email per accedere al tuo account",
    signInWith: "Accedi con",
    signOut: "Esci",
    signUp: "Registrati",
    signUpAction: "Crea un account",
    signUpDescription: "Inserisci le tue informazioni per creare un account",
    signUpEmail: "Controlla la tua email per il link di verifica.",
    sessions: "Sessioni",
    sessionsDescription: "Gestisci le tue sessioni attive e revoca l'accesso.",
    setPassword: "Imposta password",
    setPasswordDescription: "Clicca sul pulsante qui sotto per ricevere un'email per impostare una password per il tuo account.",
    settings: "Impostazioni",
    save: "Salva",
    security: "Sicurezza",
    switchAccount: "Cambia account",
    trustDevice: "Fidati di questo dispositivo",
    twoFactor: "Due fattori",
    twoFactorAction: "Verifica codice",
    twoFactorDescription: "Inserisci la tua password monouso per continuare",
    twoFactorCardDescription: "Aggiungi un ulteriore livello di sicurezza al tuo account.",
    twoFactorDisableInstructions: "Inserisci la tua password per disattivare l'autenticazione a due fattori.",
    twoFactorEnableInstructions: "Inserisci la tua password per attivare l'autenticazione a due fattori",
    twoFactorEnabled: "L'autenticazione a due fattori è stata attivata",
    twoFactorDisabled: "L'autenticazione a due fattori è stata disattivata",
    twoFactorPrompt: "Autenticazione a due fattori",
    twoFactorTotpLabel: "Scansiona il codice QR con il tuo autenticatore",
    sendVerificationCode: "Invia codice di verifica",
    unlink: "Scollega",
    updatedSuccessfully: "aggiornato con successo",
    username: "Nome utente",
    usernameDescription: "Inserisci il nome utente che desideri utilizzare per accedere.",
    usernameInstructions: "Utilizza massimo 32 caratteri.",
    usernamePlaceholder: "Nome utente",
    signInUsernamePlaceholder: "Nome utente o email",
    verifyYourEmail: "Verifica la tua email",
    verifyYourEmailDescription: "Verifica il tuo indirizzo email. Controlla la tua casella di posta per l'email di verifica. Se non hai ricevuto l'email, clicca sul pulsante qui sotto per inviarla nuovamente.",
    goBack: "Torna indietro",
    invalidPassword: "Password non valida",
    invalidEmailOrPassword: "Email o password non valide",
    passwordTooShort: "Password troppo corta",
    uploadAvatar: "Carica avatar"
}