// Replace with "@daveyplate/better-auth-ui" import
import { type AuthLocalization } from "../../../../src/lib/auth-localization"

export const portugueseLocalization: AuthLocalization = {
    account: "Conta",
    accounts: "Contas",
    accountsDescription: "Gerencie suas contas atualmente conectadas.",
    accountsInstructions: "Entre em uma conta adicional.",
    addAccount: "Adicionar conta",
    addPasskey: "Adicionar chave de acesso",
    alreadyHaveAnAccount: "Já tem uma conta?",
    avatar: "Avatar",
    avatarDescription: "Clique no avatar para enviar um avatar personalizado dos seus arquivos.",
    avatarInstructions: "Um avatar é opcional, mas altamente recomendado.",
    backupCodeRequired: "Código de backup é obrigatório",
    backupCodes: "Códigos de backup",
    backupCodesDescription: "Guarde estes códigos de backup em um local seguro. Você pode usá-los para acessar sua conta se perder seu método de autenticação de dois fatores.",
    backupCodePlaceholder: "Código de backup",
    backupCode: "Código de backup",
    backupCodeAction: "Recuperar conta",
    cancel: "Cancelar",
    changePassword: "Alterar senha",
    changePasswordDescription: "Digite sua senha atual e uma nova senha.",
    changePasswordInstructions: "Por favor, use pelo menos 8 caracteres.",
    changePasswordSuccess: "Sua senha foi alterada.",
    confirmPassword: "Confirmar senha",
    confirmPasswordPlaceholder: "Confirmar senha",
    confirmPasswordRequired: "Confirmação de senha é obrigatória",
    continueWithAuthenticator: "Continuar com autenticador",
    copiedToClipboard: "Copiado para a área de transferência",
    copyAllCodes: "Copiar todos os códigos",
    continue: "Continuar",
    currentPassword: "Senha atual",
    currentPasswordPlaceholder: "Senha atual",
    currentSession: "Sessão atual",
    delete: "Excluir",
    deleteAvatar: "Excluir avatar",
    deleteAccount: "Excluir conta",
    deleteAccountDescription: "Remova permanentemente sua conta e todo o conteúdo. Esta ação não pode ser desfeita, então por favor, prossiga com cuidado.",
    deleteAccountInstructions: "Por favor, confirme a exclusão da sua conta. Esta ação não pode ser desfeita, então por favor, prossiga com cuidado.",
    deleteAccountVerify: "Por favor, verifique seu email para confirmar a exclusão da sua conta.",
    deleteAccountSuccess: "Sua conta foi excluída.",
    deleteAccountNotFresh: "Você precisa ter feito login recentemente para excluir sua conta.",
    disable: "Desativar",
    disabledCredentialsDescription: "Escolha um provedor para entrar em sua conta",
    dontHaveAnAccount: "Não tem uma conta?",
    email: "Email",
    emailDescription: "Digite o endereço de email que você deseja usar para fazer login.",
    emailInstructions: "Por favor, digite um endereço de email válido.",
    emailInvalid: "Endereço de email é inválido",
    emailIsTheSame: "Email é o mesmo",
    emailPlaceholder: "m@exemplo.com",
    emailRequired: "Endereço de email é obrigatório",
    emailVerifyChange: "Por favor, verifique seu email para confirmar a mudança.",
    emailVerification: "Por favor, verifique seu email para o link de confirmação.",
    enable: "Ativar",
    error: "Erro",
    isInvalid: "é inválido",
    isRequired: "é obrigatório",
    isTheSame: "é o mesmo",
    forgotAuthenticator: "Esqueceu o autenticador?",
    forgotPassword: "Esqueceu a senha",
    forgotPasswordAction: "Enviar link de redefinição",
    forgotPasswordDescription: "Digite seu email para redefinir sua senha",
    forgotPasswordEmail: "Verifique seu email para o link de redefinição de senha.",
    forgotPasswordLink: "Esqueceu a senha?",
    invalidTwoFactorCookie: "Cookie de dois fatores inválido",
    link: "Vincular",
    magicLink: "Link mágico",
    magicLinkAction: "Enviar link mágico",
    magicLinkDescription: "Digite seu email para receber um link mágico",
    magicLinkEmail: "Verifique seu email para o link mágico",
    emailOTP: "Código de email",
    emailOTPSendAction: "Enviar código",
    emailOTPVerifyAction: "Verificar código",
    emailOTPDescription: "Digite seu email para receber um código",
    emailOTPVerificationSent: "Por favor, verifique seu email para o código de confirmação.",
    name: "Nome",
    nameDescription: "Por favor, digite seu nome completo ou um nome de exibição.",
    nameInstructions: "Por favor, use no máximo 32 caracteres.",
    namePlaceholder: "Nome",
    newPassword: "Nova senha",
    newPasswordPlaceholder: "Nova senha",
    newPasswordRequired: "Nova senha é obrigatória",
    oneTimePassword: "Senha de uso único",
    orContinueWith: "Ou continuar com",
    passkey: "Chave de acesso",
    passkeys: "Chaves de acesso",
    passkeysDescription: "Gerencie suas chaves de acesso para entrada segura.",
    passkeysInstructions: "Acesse sua conta com segurança sem usar uma senha.",
    password: "Senha",
    passwordPlaceholder: "Senha",
    passwordRequired: "Senha é obrigatória",
    passwordsDoNotMatch: "Senhas não correspondem",
    providers: "Provedores",
    providersDescription: "Conecte sua conta a um serviço de terceiros.",
    recoverAccount: "Recuperar conta",
    recoverAccountAction: "Recuperar conta",
    recoverAccountDescription: "Por favor, digite um código de backup para acessar sua conta",
    rememberMe: "Lembrar de mim",
    resendCode: "Reenviar código",
    resendVerificationEmail: "Reenviar email de verificação",
    resetPassword: "Redefinir senha",
    resetPasswordAction: "Salvar nova senha",
    resetPasswordDescription: "Digite sua nova senha abaixo",
    resetPasswordInvalidToken: "Link de redefinição de senha inválido",
    resetPasswordSuccess: "Senha redefinida com sucesso",
    requestFailed: "Solicitação falhou",
    revoke: "Revogar",
    signIn: "Entrar",
    signInAction: "Entrar",
    signInDescription: "Digite seu email abaixo para entrar em sua conta",
    signInUsernameDescription: "Digite seu nome de usuário ou email para entrar em sua conta",
    signInWith: "Entrar com",
    signOut: "Sair",
    signUp: "Registrar",
    signUpAction: "Criar conta",
    signUpDescription: "Digite seus dados para criar uma conta",
    signUpEmail: "Verifique seu email para o link de confirmação.",
    sessions: "Sessões",
    sessionsDescription: "Gerencie suas sessões ativas e revogue o acesso.",
    setPassword: "Definir senha",
    setPasswordDescription: "Clique no botão abaixo para receber um email para definir uma senha para sua conta.",
    settings: "Configurações",
    save: "Salvar",
    security: "Segurança",
    switchAccount: "Trocar conta",
    trustDevice: "Confiar neste dispositivo",
    twoFactor: "Dois fatores",
    twoFactorAction: "Verificar código",
    twoFactorDescription: "Por favor, digite sua senha de uso único para continuar",
    twoFactorCardDescription: "Adicione uma camada extra de segurança à sua conta.",
    twoFactorDisableInstructions: "Por favor, digite sua senha para desativar 2FA.",
    twoFactorEnableInstructions: "Por favor, digite sua senha para ativar 2FA",
    twoFactorEnabled: "Autenticação de dois fatores foi ativada",
    twoFactorDisabled: "Autenticação de dois fatores foi desativada",
    twoFactorPrompt: "Autenticação de dois fatores",
    twoFactorTotpLabel: "Escaneie o código QR com seu autenticador",
    sendVerificationCode: "Enviar código de verificação",
    unlink: "Desvincular",
    updatedSuccessfully: "atualizado com sucesso",
    username: "Nome de usuário",
    usernameDescription: "Digite o nome de usuário que você deseja usar para fazer login.",
    usernameInstructions: "Por favor, use no máximo 32 caracteres.",
    usernamePlaceholder: "Nome de usuário",
    signInUsernamePlaceholder: "Nome de usuário ou email",
    verifyYourEmail: "Verifique seu email",
    verifyYourEmailDescription: "Por favor, verifique seu endereço de email. Verifique sua caixa de entrada para o email de confirmação. Se você não recebeu o email, clique no botão abaixo para reenviar.",
    goBack: "Voltar",
    invalidPassword: "Senha inválida",
    invalidEmailOrPassword: "Email ou senha inválidos",
    passwordTooShort: "Senha muito curta",
    uploadAvatar: "Enviar avatar"
}
