// Replace with "@daveyplate/better-auth-ui" import
import { type AuthLocalization } from "../../../../src/lib/auth-localization"

export const spanishLocalization: AuthLocalization = {
    account: "Cuenta",
    accounts: "Cuentas",
    accountsDescription: "Gestione sus cuentas actualmente conectadas.",
    accountsInstructions: "Inicie sesión en una cuenta adicional.",
    addAccount: "Añadir cuenta",
    addPasskey: "Añadir clave de acceso",
    alreadyHaveAnAccount: "¿Ya tiene una cuenta?",
    avatar: "Avatar",
    avatarDescription: "Haga clic en el avatar para cargar uno personalizado desde sus archivos.",
    avatarInstructions: "Un avatar es opcional pero muy recomendable.",
    backupCodeRequired: "Se requiere un código de respaldo",
    backupCodes: "Códigos de respaldo",
    backupCodesDescription: "Guarde estos códigos de respaldo en un lugar seguro. Puede utilizarlos para acceder a su cuenta si pierde su método de autenticación de dos factores.",
    backupCodePlaceholder: "Código de respaldo",
    backupCode: "Código de respaldo",
    backupCodeAction: "Recuperar cuenta",
    cancel: "Cancelar",
    changePassword: "Cambiar contraseña",
    changePasswordDescription: "Introduzca su contraseña actual y una nueva contraseña.",
    changePasswordInstructions: "Por favor, utilice al menos 8 caracteres.",
    changePasswordSuccess: "Su contraseña ha sido cambiada.",
    confirmPassword: "Confirmar contraseña",
    confirmPasswordPlaceholder: "Confirmar contraseña",
    confirmPasswordRequired: "Se requiere confirmación de contraseña",
    continueWithAuthenticator: "Continuar con autenticador",
    copiedToClipboard: "Copiado al portapapeles",
    copyAllCodes: "Copiar todos los códigos",
    continue: "Continuar",
    currentPassword: "Contraseña actual",
    currentPasswordPlaceholder: "Contraseña actual",
    currentSession: "Sesión actual",
    delete: "Eliminar",
    deleteAvatar: "Eliminar avatar",
    deleteAccount: "Eliminar cuenta",
    deleteAccountDescription: "Elimine permanentemente su cuenta y todo su contenido. Esta acción no es reversible, así que proceda con precaución.",
    deleteAccountInstructions: "Por favor, confirme la eliminación de su cuenta. Esta acción no es reversible, así que proceda con precaución.",
    deleteAccountVerify: "Por favor, compruebe su correo electrónico para verificar la eliminación de su cuenta.",
    deleteAccountSuccess: "Su cuenta ha sido eliminada.",
    deleteAccountNotFresh: "Debe haber iniciado sesión recientemente para eliminar su cuenta.",
    disable: "Desactivar",
    disabledCredentialsDescription: "Elija un proveedor para iniciar sesión en su cuenta",
    dontHaveAnAccount: "¿No tiene una cuenta?",
    email: "Correo electrónico",
    emailDescription: "Introduzca la dirección de correo electrónico que desea utilizar para iniciar sesión.",
    emailInstructions: "Por favor, introduzca una dirección de correo electrónico válida.",
    emailInvalid: "La dirección de correo electrónico no es válida",
    emailIsTheSame: "El correo electrónico es el mismo",
    emailPlaceholder: "m@example.com",
    emailRequired: "Se requiere una dirección de correo electrónico",
    emailVerifyChange: "Por favor, compruebe su correo electrónico para verificar el cambio.",
    emailVerification: "Por favor, compruebe su correo electrónico para el enlace de verificación.",
    enable: "Activar",
    error: "Error",
    isInvalid: "no es válido",
    isRequired: "es requerido",
    isTheSame: "es el mismo",
    forgotAuthenticator: "¿Olvidó el autenticador?",
    forgotPassword: "Olvidé mi contraseña",
    forgotPasswordAction: "Enviar enlace de restablecimiento",
    forgotPasswordDescription: "Introduzca su correo electrónico para restablecer su contraseña",
    forgotPasswordEmail: "Compruebe su correo electrónico para el enlace de restablecimiento de contraseña.",
    forgotPasswordLink: "¿Olvidó su contraseña?",
    invalidTwoFactorCookie: "Cookie de autenticación de dos factores no válida",
    link: "Vincular",
    magicLink: "Enlace mágico",
    magicLinkAction: "Enviar enlace mágico",
    magicLinkDescription: "Introduzca su correo electrónico para recibir un enlace mágico",
    magicLinkEmail: "Compruebe su correo electrónico para el enlace mágico",
    emailOTP: "Código por correo electrónico",
    emailOTPSendAction: "Enviar código",
    emailOTPVerifyAction: "Verificar código",
    emailOTPDescription: "Introduzca su correo electrónico para recibir un código",
    emailOTPVerificationSent: "Por favor, compruebe su correo electrónico para el código de verificación.",
    name: "Nombre",
    nameDescription: "Por favor, introduzca su nombre completo o un nombre para mostrar.",
    nameInstructions: "Por favor, utilice un máximo de 32 caracteres.",
    namePlaceholder: "Nombre",
    newPassword: "Nueva contraseña",
    newPasswordPlaceholder: "Nueva contraseña",
    newPasswordRequired: "Se requiere una nueva contraseña",
    oneTimePassword: "Contraseña de un solo uso",
    orContinueWith: "O continuar con",
    passkey: "Clave de acceso",
    passkeys: "Claves de acceso",
    passkeysDescription: "Gestione sus claves de acceso para un acceso seguro.",
    passkeysInstructions: "Acceda a su cuenta de forma segura sin contraseña.",
    password: "Contraseña",
    passwordPlaceholder: "Contraseña",
    passwordRequired: "Se requiere contraseña",
    passwordsDoNotMatch: "Las contraseñas no coinciden",
    providers: "Proveedores",
    providersDescription: "Conecte su cuenta con un servicio de terceros.",
    recoverAccount: "Recuperar cuenta",
    recoverAccountAction: "Recuperar cuenta",
    recoverAccountDescription: "Por favor, introduzca un código de respaldo para acceder a su cuenta",
    rememberMe: "Recordarme",
    resendCode: "Reenviar código",
    resendVerificationEmail: "Reenviar correo de verificación",
    resetPassword: "Restablecer contraseña",
    resetPasswordAction: "Guardar nueva contraseña",
    resetPasswordDescription: "Introduzca su nueva contraseña a continuación",
    resetPasswordInvalidToken: "Enlace de restablecimiento de contraseña no válido",
    resetPasswordSuccess: "Contraseña restablecida con éxito",
    requestFailed: "La solicitud falló",
    revoke: "Revocar",
    signIn: "Iniciar sesión",
    signInAction: "Iniciar sesión",
    signInDescription: "Introduzca su correo electrónico a continuación para iniciar sesión en su cuenta",
    signInUsernameDescription: "Introduzca su nombre de usuario o correo electrónico para iniciar sesión en su cuenta",
    signInWith: "Iniciar sesión con",
    signOut: "Cerrar sesión",
    signUp: "Registrarse",
    signUpAction: "Crear una cuenta",
    signUpDescription: "Introduzca su información para crear una cuenta",
    signUpEmail: "Compruebe su correo electrónico para el enlace de verificación.",
    sessions: "Sesiones",
    sessionsDescription: "Gestione sus sesiones activas y revoque el acceso.",
    setPassword: "Establecer contraseña",
    setPasswordDescription: "Haga clic en el botón de abajo para recibir un correo electrónico para establecer una contraseña para su cuenta.",
    settings: "Configuración",
    save: "Guardar",
    security: "Seguridad",
    switchAccount: "Cambiar de cuenta",
    trustDevice: "Confiar en este dispositivo",
    twoFactor: "Dos factores",
    twoFactorAction: "Verificar código",
    twoFactorDescription: "Por favor, introduzca su contraseña de un solo uso para continuar",
    twoFactorCardDescription: "Añada una capa adicional de seguridad a su cuenta.",
    twoFactorDisableInstructions: "Por favor, introduzca su contraseña para desactivar 2FA.",
    twoFactorEnableInstructions: "Por favor, introduzca su contraseña para activar 2FA",
    twoFactorEnabled: "La autenticación de dos factores ha sido activada",
    twoFactorDisabled: "La autenticación de dos factores ha sido desactivada",
    twoFactorPrompt: "Autenticación de dos factores",
    twoFactorTotpLabel: "Escanee el código QR con su autenticador",
    sendVerificationCode: "Enviar código de verificación",
    unlink: "Desvincular",
    updatedSuccessfully: "actualizado con éxito",
    username: "Nombre de usuario",
    usernameDescription: "Introduzca el nombre de usuario que desea utilizar para iniciar sesión.",
    usernameInstructions: "Por favor, utilice un máximo de 32 caracteres.",
    usernamePlaceholder: "Nombre de usuario",
    signInUsernamePlaceholder: "Nombre de usuario o correo electrónico",
    verifyYourEmail: "Verifique su correo electrónico",
    verifyYourEmailDescription: "Por favor, verifique su dirección de correo electrónico. Compruebe su bandeja de entrada para el correo de verificación. Si no ha recibido el correo, haga clic en el botón a continuación para reenviarlo.",
    goBack: "Volver",
    invalidPassword: "Contraseña no válida",
    invalidEmailOrPassword: "Correo electrónico o contraseña no válidos",
    passwordTooShort: "Contraseña demasiado corta",
    uploadAvatar: "Cargar avatar"
}
